MODULE F_CALLEE
    USE, INTRINSIC :: ISO_C_BINDING
    IMPLICIT NONE
    CONTAINS
        FUNCTION GET_FPTR(LIBRARY, FNAME) RESULT(PTR)
            IMPLICIT NONE
            CHARACTER :: LIBRARY(*), FNAME(*)
            INTEGER(KIND=SELECTED_INT_KIND(18)) :: PTR
            TYPE(C_FUNPTR) :: CPTR
            INTERFACE
              SUBROUTINE CFUNC(LIB, F_N, CPTR_) &
                BIND(C, NAME="c_func")
                USE, INTRINSIC :: ISO_C_BINDING
                CHARACTER(C_CHAR) :: LIB(*), F_N(*)
                TYPE(C_FUNPTR) :: CPTR_
              END SUBROUTINE CFUNC
            END INTERFACE
            CALL CFUNC(LIBRARY, FNAME, CPTR)
            PTR = TRANSFER(CPTR, PTR)
        END FUNCTION GET_FPTR

        SUBROUTINE TEST_FPTR(PTR)
          IMPLICIT NONE
          INTEGER(KIND=SELECTED_INT_KIND(18)) :: PTR       
          INTERFACE
            SUBROUTINE DUMMYSUBR() BIND(C)
              IMPORT
              IMPLICIT NONE
            END SUBROUTINE DUMMYSUBR
          END INTERFACE
          TYPE(C_FUNPTR) :: CFPTR
          PROCEDURE(DUMMYSUBR), POINTER :: FN

          CFPTR = TRANSFER(PTR, CFPTR)
          CALL C_F_PROCPOINTER(CFPTR, FN)
          CALL FN();
        END SUBROUTINE TEST_FPTR

END MODULE F_CALLEE
