PROGRAM MAIN
    
    USE F_CALLEE
    
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)) :: PTR = 0
    CHARACTER :: LIBNAME(10),FUNCNAME(10)
    TYPE(C_FUNPTR) :: CFPTR
    
    LIBNAME(1) = "L"
    LIBNAME(2) = "I"
    LIBNAME(3) = "B"
    LIBNAME(4) = "R"
    LIBNAME(5) = "A"
    LIBNAME(6) = "R"
    LIBNAME(7) = "Y"
    LIBNAME(8) = CHAR(0)
    
    FUNCNAME(1) = "F"
    FUNCNAME(2) = "U"
    FUNCNAME(3) = "N"
    FUNCNAME(4) = "C"
    FUNCNAME(5) = CHAR(0)
    
    PRINT *, 'PTR:', PTR
    PTR = GET_FPTR(LIBNAME,FUNCNAME)
    PRINT *, 'PTR:', PTR
    CALL TEST_FPTR(PTR);

END PROGRAM MAIN
